Hdbscan (#21)
* Initial commit of attempt to incorporate parts of reference code to diagnose fuzzies

* Safety commit of hdbscan

* Safety commit

* Issue in hierarchy or condensation.

* Split some methods

* Versioning 0.1.8

* hotfix - better memory management

* hotfix - documentation for hdbscan plotting function

* hotfix, documentation example error

* hotfix - somehow lgsl found its way back into Makevars

* Fixes for a broken sparse-test, documentation issues.

* hotfix

* Updated readme

* Revisions for CRAN.
Modified pq.h to avoid all-in-one-cluster results.

* Updated vignettes

* Update dbscan.R

* as.dendrogram
some attempted fixes for CRAN

* safety commit

* Removed dbscan from R

* Hotfix - typo in openmp code caused failure to compile if openmp was missing.

* Fix "tutorial" (typo & verbosity list issue) (#18)

* Fixing very key typo in "tutorial"

* Default list boolean bug, breaking tutorial

buildEdgeMatrix: throwing "Error: not compatible with requested type" error without verbosity, because a list is used as input for verbosity as default instead of a boolean. It was breaking the tutorial on the homepage!

Error for buildEdgeMatrix:

> edges_vis <- buildEdgeMatrix(data = initial_diag, neighbors = neighbors_vis, verbose = TRUE)
|----|----|----|----|----|----|----|----|----|----|
**************************************************|
> edges_vis <- buildEdgeMatrix(data = initial_diag, neighbors = neighbors_vis)
Error: not compatible with requested type

* Fix key typo for tutorial

Fix wording: "buildWijMaatrix" -> "buildWijMatrix"

* Fix doc key typo

Typo fixed: "buildWijMaatrix" -> "buildWijMatrix"

* Fix key typo in tutorial

Fixing typo: "buildWijMaatrix" -> "buildWijMatrix"

* Fix key typo

Typo fixed: "buildWijMaatrix" -> "buildWijMatrix"

* Hdbscan Rebase (#2)

* Initial commit of attempt to incorporate parts of reference code to diagnose fuzzies

* Safety commit of hdbscan

* Safety commit

* Issue in hierarchy or condensation.

* Split some methods

* Versioning 0.1.8

* hotfix - better memory management

* hotfix - documentation for hdbscan plotting function

* hotfix, documentation example error

* hotfix - somehow lgsl found its way back into Makevars

* Fixes for a broken sparse-test, documentation issues.

* hotfix

* Updated readme

* Revisions for CRAN.
Modified pq.h to avoid all-in-one-cluster results.

* Updated vignettes

* Update dbscan.R

* as.dendrogram
some attempted fixes for CRAN

* safety commit

* Removed dbscan from R

* Hotfix - typo in openmp code caused failure to compile if openmp was missing.

* Revert "Hdbscan Rebase (#2)"

This reverts commit 8b78a50a636a8fb4ba3e9559edefdba86fe5b7a5.

* Fix verbosity in doc.

* Added parameter for number of threads.
Improved efficiency of hdbscan (dramatically).
Removed facevectors.
Removed OS_type line from DESCRIPTION file.

* hotfix to neighbor sort

* Final testing for CRAN resubmission.

* As submitted to CRAN.